### ISSUE TITLE
Have anonymous type "short" syntax lead to `(default, never)`

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe-evolution#17]
To clarify the title: I would like `{ foo:Int }` to mean `{ var foo(default, never):Int; }` rather than the current `{ var foo(default, default):Int; }`.

Is this something we would even consider? If so, I will make a proper proposal.

**Comment by nadako** [comment]
Doesn't sound like a good idea to change access modifiers depending on notation, however I'd like to have a way to specify access in the short version (but this was [rejected](https://github.com/HaxeFoundation/haxe/issues/2565) before)

**Comment by back2dos** [comment]
> Doesn't sound like a good idea to change access modifiers depending on notation

I disagree. Also, if you provided an argument it would be easier for me to respond. Whatever your reasoning may be, I think it is backwards:

If we have two kinds of syntax, should they not mean two different things? Or reframed otherwise: what's the point of the short syntax then? It has repeatedly been a source of confusion. It adds nothing to the language, so we might as well remove it. At the same time, [now that Nicolas has put his FP hipster hat on](https://github.com/HaxeFoundation/haxe-evolution/pull/8#issuecomment-262709295), I propose introducing a concise syntax for declaring immutable structures. I already have an idea what it might look like ;)

**Comment by nadako** [comment]
I might be wrong, but I think short syntax is meant to be used for small inline types (e.g. `var obj:{a:Int, b:String}`) while "full" one is for typedef'd structures with metadata, documentation and whatnot. Other than that they should be interchangeable. Is that right, @ncannasse?

Anyway, I'm personally all for introducing more immutability, but I don't think Haxe is currently heading that way (again, correct me if I'm wrong), so it would be more logical to have explicit readonly fields (e.g. `{ readonly foo:Int }`, or simply support `{ foo(default,never):Int }` for the short syntax).

---

Talking about immutability, I think it would be even better to have some kind of recursive immutable "view" types, similar to C++ const? E.g. `var immutableStruct:const(MutableStruct)` that would provide readonly access for any type and its children (e.g. structure/class fields, enum constructor arguments and so on) while still keeping reference to the original type (so type checking, variance and pattern matching works as expected).

I experimented with that a bit in my toy compiler and didn't see a lot of difficulties with implementing that. Probably I should try writing an evolution proposal for that...

**Comment by fponticelli** [comment]
For what is worth I'd really love to have short syntax for immutable structures. `{ !field: 1 }` would be concise enough in my opinion. Yes, it can be done with a macro (not the syntax, the immutability). Yes, macro suck for these kind of things.

**Comment by ncannasse** [comment]
Would not a `haxe.Immutable<{ field : Int }>` be enough? (we can use a macro to implement it)
If you want to add mutable fields, I think you should still be able to do :  { > haxe.IMutable({...}), isMutable : Bool }

**Comment by nadako** [comment]
> Would not a haxe.Immutable<{ field : Int }> be enough? (we can use a macro to implement it)

I'm using such a macro (`@:genericBuild(...) class Const<T>`) in my work project, which seemed to be a great idea at first, but it has quite a list of problems, some of them are (in no particular order):

 * the macro slowdown is VERY significant when you use a lof of those types
 * you can't do `typedef A<T> = { foo:Const<T> }`, since a macro won't know what to build from that
 * generated type name looks somewhat like `Const_original_pack_OriginalName` which is quite ugly and can be confusing in autocompletion
 * generated type/module depends on the module the macro was called from which screws up compilation/completion server (I still have no idea how to fix that properly in my codebase)
 * type parameter invariance creates obstacles when you try to use generated constant types in type parameters (for collections) which can be only worked around by using `cast`
 * you can't generate a `Const` version of an enum that will be compatible with the original (since it'll be a completely different type)

There are probably more of them which I can't remember right now, but these alone are enough to agree with @fponticelli that "macro suck for these kind of things" :) So I'm really in favor of proper compiler support for that.

**Comment by back2dos** [comment]
> I might be wrong, but I think short syntax is meant to be used for small inline types (e.g. `var obj:{a:Int, b:String}`) while "full" one is for typedef'd structures with metadata, documentation and whatnot. Other than that they should be interchangeable.

They are not interchangeable. The short syntax picks exactly one kind of field access. The least useful one. Let's compare:

```
{
  var foo:Int;
  var bar:Int;
}

//versus.:

{
  foo:Int,
  bar:Int,
}
```

So that saves us one token per field? Wow, such awesome! Of all the choices `(default, default)` is the least useful one. It even leads to problems like this:

```
function sayHello(to:{ name:String })
  trace("hello, ${to.name}!");

sayHello(new Person("Dan"));
```

Unless `Person` defines `name` to have `default` write access it won't work, which rules out `null` *and* `set`. It really should not be doing that ...

> Anyway, I'm personally all for introducing more immutability, but I don't think Haxe is currently heading that way (again, correct me if I'm wrong), 

If I am not mistaken, this is a platform to affect where Haxe is currently heading. If it is not heading towards something that you're all for, this an opportunity to correct that, no?

-------

> Talking about immutability, I think it would be even better to have some kind of recursive immutable "view" types, similar to C++ const?

It would not be better, it would just be different. It would be a lot harder to do and misses the point of what I want. What I am after is a straight forward to declare immutable structure types in Haxe. And yes, sometimes the immutable structures should contain mutable values. That is perfect. From my understanding it is no different from OCaml ...

Performance cultists will use classes anyway. For everyone else, immutability is the more sensible default IMO, especially if going from immutable to mutable objects requires sprinkling in just a few `var` keywords, which makes perfect sense because fields go from being *immutable* to being ***var**iable*.

I do get what you're after, but what I would like to propose is a small change that gives an existing but rather useless syntax a more useful meaning. If that's not going to happen, then ok, let's close this and not bother. We can discuss immutability at large, but this proposal is hardly a good basis for it.

**Comment by nadako** [comment]
> The short syntax picks exactly one kind of field access.
...
> The least useful one. 

Well that's debatable, but I'll choose to be a passive observer in this discussion for now, because I don't have a strong opinion on what you propose right now and I also kind of want more immutability in Haxe. :) Let's hear out other opinions.

> If I am not mistaken, this is a platform to affect where Haxe is currently heading. If it is not heading towards something that you're all for, this an opportunity to correct that, no?

Yeah, that's correct, sorry :-P 

> going from immutable to mutable objects requires sprinkling in just a few var keywords, which makes perfect sense because fields go from being immutable to being variable.

That makes sense, though currently this syntax is not only different in the var keyword presence, it also differs in that you can't add metadata, you have to use commas instead of semicolons and documentation is not parsed, so it's more than "var" or "no var".

As for my proposal, yeah I also get it's a different thing, so sorry about hijacking your thread :-P I'll refrain from further discussion of immutability in general and maybe prepare another proposal.

**Comment by ncannasse** [comment]
If the proposal is not about finding a way to declare immutable fields but changing the default then I'm fully opposed to it. Haxe is a multipurpose object oriented language, and while I understand immutability works well together with functional programming, it should not become the default. Including it would break a huge amount (if not all) Haxe 3 code.

**Comment by fponticelli** [comment]
Immutability is good also for object oriented programming, not just
functional.

On Sat, Jan 28, 2017 at 3:08 AM Nicolas Cannasse <notifications@github.com>
wrote:

If the proposal is not about finding a way to declare immutable fields but
changing the default then I'm fully opposed to it. Haxe is a multipurpose
object oriented language, and while I understand immutability works well
together with functional programming, it should not become the default.
Including it would break a huge amount (if not all) Haxe 3 code.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/HaxeFoundation/haxe-evolution/issues/17#issuecomment-275839525>,
or mute the thread

**Comment by Simn** [comment]
Since this proposal indeed seems to be about changing the default, this is an easy rejection like Nicolas said.

A shorter notation for `(default, never)` and perhaps `(default, null)` would indeed be nice, but should be discussed in a separate proposal.
