### ISSUE TITLE
platform '--switch' within hxml, labeled '--next' passed with hxml call.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe-evolution#42]
When building hxml I will ask my mac to open a browser.

But when creating libraries that others may try using, I want to support atleast **windows**,**mac** and **linux** from simple hxml build scripts, while where possible avoiding xml non generic solutions or complexity of special library run scripts.

```
--next
-cmd echo '<!DOCTYPE html><meta charset="UTF-8"><html><body><script src="test.js"></script></body></html>' >../binWebGL/index.html
-cmd open ../binWebGL/index.html
```

the simplest solution is a secondary file?

```
--next
--switch win: win.hxml mac: mac.hxml linux linux.hxml 
```

It seems minimum that **haxelib** should support something like **--if** or **--switch** for all currently widely used platforms, but ideally atleast just **windows**, **mac** and **linux** so that we can provide scripts to automatically open the browser at the very least.  I am sure that I have brought this up before, and I know that any suggestions that were made to me last time did not end up being simple and practical to use on projects.  It's a requirement that I have had for many years, and something that I understand is not a priority but would like it added to evolution, but would be happy with alternative hxml only solutions.

Suggestion it would be very useful to pass in a parameters  
```
haxe compile.hxml next heapsWebGL
```

```
--next heapsWebGL
# only called if the next is in the terminal call
--next
```
So that any **--next** statement that has a parameter is only run if it is called when running the hxml, this makes it much easier to use a single hxml file without clutter of one for every target or a separate build folder that then create folder level complications and user confusion.

**Comment by bendmorris** [comment]
I agree with the goal but we're bumping up against the limits of what a format like hxml should reasonably support (hierarchical structure?) There's a natural split between compiler args and build configuration: build config should be flexible and expressive, and generates a set of compiler args for a single build, which can be simple and specific. So an alternate approach would be to standardize what build configuration looks like across projects, rather than overloading hxml.

So my alternative suggestion is to *standardize a subset of OpenFL's project.xml/include.xml functionality*, because that project has already solved this problem in an elegant way. (Syntax and format are less important than functionality here, pick your favorite markup language. I'll use YAML for this example because it's concise.)

There has [also been a suggestion to add more metadata fields to haxelib.json](https://github.com/HaxeFoundation/haxe-evolution/issues/34), and include.xml solves that problem as well. If haxelib.yaml (or whatever) is present, it takes precedence over haxelib.json, and otherwise can include the same information. And while we're at it this also eliminates the need for extraParams.hxml.

```yaml
name: hxpk
version: "0.1.0"
license: "MIT"
contributors: ["bendmorris"]

src: ["src"]

flags:
- "-dce=full"

dependencies:
- format
- hxbit

section:
- if: test
  unless: no-test
  flags: ["-debug"]
  dependencies: ["unit"]
  src: ["src-tests"]
```

This generates a set of compiler args: `haxe -cp src -dce=full -lib format -lib hxbit`. If called with -Dtest, it adds extra args: `-debug -lib unit -cp src-tests`.

There might be pushback that "haxe/haxelib is not a build tool." True, but having so much fragmentation among build tools is not great and Haxe doesn't have a clear winner in that space. At minimum we should have a standard format and set of semantics that works for basic projects and is expressive enough for build tools to consume without needing to provide their own entirely separate format.

**Comment by nanjizal** [comment]
What I requested was a minor change to allow more practical use, they are rebuilding haxelib2 but that may take a long time.  I can try to add the changes to current haxelib perhaps but it would need a go ahead on a concept before trying.  The problem is if you look at 'Quick' is that every toolkit uses a different system.  I can work with that but for just working with simple js stuff it's annoying that I can't call open the browser the same way on all platforms.  That is the part that is annoying because then your library will look broken when a windows user downloads it.

**Comment by nanjizal** [comment]
I can look to make a minor change to haxelib if a simple idea is agreed but would not attempt a total change like your suggestion.

**Comment by RealyUniqueName** [comment]
I usually go with `-cmd haxe -main Run.hx --interp` and whatever I need depending on any circumstances.

**Comment by Simn** [comment]
hxml is fundamentally unsuited for something like this, so we'll need a different solution here.
